export const ADD_CONTACT = "ADD_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const CURRENT_CONTACT = "CURRENT_CONTACT";
export const ADD_BUTTON_CLICK = "ADD_BUTTON_CLICK";
