export const ADD_CONTACT = "ADD_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const CURRENT_CONTACT = "CURRENT_CONTACT";
export const ADD_BUTTON_CLICK = "ADD_BUTTON_CLICK";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const SEARCH_CONTACT = "SEARCH_CONTACT";
export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const BACKEND_FETCH_REQUEST = "BACKEND_FETCH_REQUEST";

//Fetching All Contacts data.
export const FETCH_ALL_CONTACTS_SUCCESS = "FETCH_ALL_CONTACTS_SUCCESS";
export const FETCH_ALL_CONTACTS_FAILURE = "FETCH_ALL_CONTACTS_FAILURE";

//Delete contact

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";

//UpdateContact
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE";

//AddContact
export const ADD_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE";
